### PR TITLE
Add an example using Git for dependency resolution

### PR DESCRIPTION
**Pull request by bspeice**
Should help in testing google/cargo-raze#22 and google/cargo-raze#28.
Currently broken, as BUILD files aren't generated in Git vendored dependencies.

### CODE REVIEW

**Comment by bspeice** [comment]
Note that code in google/cargo-raze#22 is broken in that it finishes without generating BUILD files in the git-vendored libraries, google/cargo-raze#28 is currently broken with some panicking `.unwrap()` calls.

**Comment by acmcarther** [comment]
Thanks for the additional example!

The repo structure is a bit weird, and as-is this example is going to get clobbered next time ./internal/update-master.sh is run. What that script does is copy the example directories from ./internal/sources into ./bazel, then run `cargo-raze` for them.

Can you move the example (sans vendored crates +generated BUILDs) into ./internal/sources as well so that update-master.sh can see it?

**Comment by acmcarther** [comment]
Ah, also can you update the new sanity_check.sh script to match https://github.com/acmcarther/cargo-raze-examples/pull/4 (putting both of the builds on the same line joined with &&)?

**Comment by bspeice** [comment]
Waiting for Travis, but I think this is what you were going for?
Can I also make a recommendation of marking bazel/ in the .gitignore so that it's more obvious where things should be added for other people contributing things in the future?

**Comment by bspeice** [comment]
The error from Travis, of which I have no idea what's going on:

```
error: use of unstable library feature 'rustc_private': this crate is being loaded from the sysroot, and unstable location; did you mean to load this crate from crates.io via `Cargo.toml` instead? (see issue #27812)
  --> non_cratesio_library/src/main.rs:22:3
   |
22 |   info!("Got result from future: {:?}", result);
   |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: this error originates in a macro outside of the current crate
```

**Comment by acmcarther** [comment]
You're missing an explicit dependency on `log` in the example.

https://github.com/bspeice/cargo-raze-examples/blob/master/internal/sources/non_cratesio_library/BUILD

For some reason you can sometimes depend on crates without explicitly depending on them, but only in unstable, and only for certain crates. 

See https://github.com/rust-lang/rust/issues/27812 for details

**Comment by bspeice** [comment]
Which is strange, because it's [definitely included in the Cargo.toml](https://github.com/acmcarther/cargo-raze-examples/pull/5/commits/c1af9ef76037b41665de3275461fcb13ac8a5a2b#diff-d0ef3413abff3050d76e051b6e94b6a8R12).
EDIT: I'm an idiot, I was looking at the wrong BUILD file to notice that it wasn't being included properly.

**Comment by acmcarther** [comment]
I linked the handwritten example BUILD file for the example (not a generated build file). You missed the `        //non_cratesio_library/cargo:log` dep.

**Comment by acmcarther** [comment]
This LGTM. I feel like we're going to want to probably reduce the number of whole examples back to two-ish (one per genmode) to reduce the number of redundant compilations of crates and speed up CI, but its not a big deal for now. Not yet sure the best way to do that and still have the features "accessible".

Thanks again!

**Pull request merged**
