### PR TITLE
Add a non-Crates.io remote example

### PR DESCRIPTION
**Pull request by bspeice**
Adds an extra example to demonstrate [google/cargo_raze#31](https://github.com/google/cargo-raze/pull/31). Currently is incredibly basic because of issues outlined there.

### CODE REVIEW

**Comment by bspeice** [comment]
Still pretty basic, but at least it's non-trivial now.

**Comment by acmcarther** [comment]
Does it make sense to add the non-cratesio example into one of the existing workspaces? I'm just worried that this is going to further increase the smoketest time.

Would be nice to keep it discoverable though.. not sure the best way to do that. Perhaps an outline later in the README?

EDIT: I just realized two things:

1) This is passing without the feature added. Thats weird (don't have a chance to investigate _why_ at the moment though)
2) The non-remote version of this is already a separate dir. Hmm.

**Comment by bspeice** [comment]
Is it possible that it's passing because cargo raze isn't actually generating the new BUILD files during test? It would pick up the BUILD files from when I was testing [google/cargo-raze#31](https://github.com/google/cargo-raze/pull/31).
Might I also suggest that this repository host a WORKSPACE before the BUILD files get generated? The idea then would be that this repo is a clean copy, and cargo-vendor/cargo-raze get run as part of the build process.

**Comment by acmcarther** [comment]
I think its because the new sources were added to bazel/, not internal/sources/. CI is clobbering the additions.

I should set up a CI check to block additions to bazel/ except from the master branch itself. I don't feel strongly about bundling the generation and sources in one PR per-se, but it leads to a confusing experience.

**Comment by acmcarther** [comment]
That wasn't entirely clear:

The workflow I've been following is this:

1) Add new sources to internal/sources, and never directly touch bazel/ except for `WORKSPACE`
2) Update master occasionally (but perhaps in the future via cron) with the generated files using the internal/update-master.sh script.

**Comment by bspeice** [comment]
Yep, I had copied things to `bazel/` without using `update_master.sh` because it failed on the "chicken and egg" problem you've mentioned previously when running through the smoke test.

And one note if you do go down the CI checking `master` path - be careful that PR's aren't submitted with that person's `master` instead of `acmcarther` as the `origin`.

On the whole though, I like the idea of having this repo as a source of examples and an implicit smoke test, but it is a bit difficult to manage the workflow of it correctly. I won't have time for a day or two, but I'd be interested in trying to bundle the examples in a different way so that we can (a) test using local versions of `cargo-raze` (and avoid the chicken-and-egg of new features there) and (b) not have to write PR's in a very specific way that (I at least) end up breaking.

**Comment by acmcarther** [comment]
My current thinking is that merging this repository and google/cargo-raze is probably the best of all options. It lets the changes occur atomically, and greatly simplifies the CI process. In my head, an alternative proposal ought to be about as simple as that.

I'm still a fan of making _materializing_ the examples (in the form of putting them in some analogous bazel/ dir) an administrative & automated rather than human step. That is to say, the physical examples would just be an artifact for human consumption, generated from what is basically a glorified test suite. This keeps PRs pretty small (no vendoring in a feature PR), and I think is all around a useful distinction to be made.

---

FWIW, the reason this repo was broken out in the first place was because I had not separated out the example definition, and the "materialization" process out originally, and also I was worried that `cargo publish` was going to be packing up the example sources into the crates

With that in mind, a final file structure like the following is interesting to me
```
cargo-raze
├── impl
│  ├── src
│  ├── Cargo.toml
│  └── Cargo.lock
├── examples
│  ├── bazel
│  │  ├── vendored
│  │  └── remote
│  └── DO_NOT_EDIT_HERE.md
├── smoke_test
│  ├── vendored
│  └── remote
└── README.md
```
EDIT:
- ready to bikeshed over the whole thing, the most important thing is (1) getting things in the same repo and (2) making the distinction between examples and smoketest clearer
- added more stuff to filetree

**Comment by bspeice** [comment]
Just as long as there's a clear "NO SERIOUSLY DON'T TOUCH THIS DIRECTORY" notice I'm good to go.

**Comment by bspeice** [comment]
Not 100% sure why this is open, but given that it's over a year old and the original repository the PR is coming from is gone, closing.

**Pull request closed without merging**
